module read_input_module

  ! -----------------------------------------------------------------
  ! This module is used to read the input file. When reading the
  ! input file it is important to realize that there are two type of
  ! variables:
  !
  ! 1) Variables that are used by amrex to generate the mesh.
  !    These variables are labelled with "amr" and with 
  !    "geometry" in the input file. The value of such
  !     variables is read from the amrex initialization routines
  !    so in the following module they are used only
  !    to ensure self-consistency of the input.
  !
  !    Among these variables, the following must be specified:
  !     a) geometry.prob_lo: Coordinates of the bottom-left corner of
  !                          the domain (x,y). Distances are in meters
  !     b) geometry.prob_hi: Coordinates of the top-right corner of
  !                          the domain (x,y). Distances are in meters
  !     c) amr.n_cell: Number of cells in each direction (x,y)
  !     d) amr.max_level: Maximum amrex level (starting from 0)
  !
  !    The following can be omitted, in which case they will
  !    assume the default value:
  !     a) amr.v (default: 0)
  !     b) amr.ref_ratio (default: 2 for each level)
  !     c) amr.blocking_factor (default: 8)
  !     d) amr.max_grid_size (default: 32)
  !
  ! 2) Variables that are used from the rest of the code. Such
  !    variables have a diverse set of labels and are read
  !    by the routine specified in this module. All these
  !    variables are optional, if not specified they will
  !    be assigned the values given in set_default_values
  ! -----------------------------------------------------------------
  
  use amrex_amr_module
  use amrex_linear_solver_module
  
  implicit none 

  private

  ! -----------------------------------------------------------------
  ! Public variables (read from input file)
  ! -----------------------------------------------------------------

  ! --- Variables that control the length of the simulation ---

  ! Time step [s]
  public :: time_dt
  ! Maximum number of time steps
  public :: time_step_max  
  ! Maximum simulated time [s]
  public :: time_max
  ! Maximum fractional change of the timestep between two
  ! successive timesteps
  public :: time_ddt_max

  ! --- Variables for the geometry of the heat transfer domain ---

  ! Select type of geometry to simulate (Slab, West or West_rectangular)
  public :: geom_name
  ! West geometry: Coordinates for the center of the cooling pipe 
  public :: geom_cool_pipe_cntr
  ! West geometry: Radius of the cooling pipe [m]
  public :: geom_cool_pipe_radius

  ! --- Variables that control the grid generated by amrex ---

  ! How often to check if regrid is necessary (in number of time steps)
  public :: regrid_int
  ! Distance from the free surface that triggers regridding [m].
  ! One value for each level larger than 0 must be provided
  public :: regrid_dist

  ! --- Variables for the heat solver ---

  ! Parameters to plot the cooling fluxes as a function of
  ! the temperature. Array with 5 elements: 1) on-off switch,
  ! with 1 = on and 0 = off, 2) minimum temperature
  ! 3) maximum temperature, 4) temperature resolution
  ! 5) incoming heat flux
  public :: heat_cooling_debug
  ! Activate or deactivate thermionic cooling (1 = on, 0 = off)
  public :: heat_cooling_thermionic
  ! Activate or deactivate vaporization cooling (1 = on, 0 = off)
  public :: heat_cooling_vaporization
  ! Activate or deactivate radiative cooling (1 = on, 0 = off)
  public :: heat_cooling_radiation
  ! Solver for the heat equation (explicit or implicit)
  public :: heat_solver
  ! Initial phase of the sample (solid, liquid). Relevant only
  ! if the sample is initialized at the melting temperature
  public :: heat_phase_init
  ! Type of plasma heat flux (Gaussian, Uniform, Input_file)
  public :: heat_plasma_flux_type
  ! Parameters for the plasma heat flux. An array with 5 parameters
  ! whose content depends on the type of plasma heat flux
  !  a) Gaussian heat flux, array with 5 elements: 1) switching on,
  !     time [s], 2) switching off time [s], 3) peak magnitude [W/m^2],
  !     4) peak position [m], 5) standard deviation [m]
  !  b) Uniform heat flux, array with 5 elements: 1) switching on
  !     time [s], 2) switching off time [s], 3) magnitude [W/m^2],
  !     4) minimum x coordinate [m], 5) maximum x coordinate [m]
  public :: heat_plasma_flux_params
  ! Name of file containing the plasma flux (used only if the plasma
  ! heat flux is of type Input_file)
  public :: heat_plasma_flux_file
  ! Type of plasma heat flux on the second exposed side for the
  ! West geometry (Gaussian, Uniform, Input_file)
  public :: heat_plasma_flux_side_type
  ! Parameters for the plasma heat flux on the second exposed side
  ! for the West geometry. Analogous to heat_plasma_flux_parameters
  public :: heat_plasma_flux_side_params
  ! Name of file containing the plasma flux on the second exposed
  ! side for the West geometry (Used only if the plasma
  ! heat flux is of type Input_file)
  public :: heat_plasma_flux_side_file
  ! Activate or deactivate reflux in the explicit heat
  ! solver (1 = on, 0 = off)
  public :: heat_reflux
  ! Edge of the simulation domain along the x direction [m]
  public :: heat_sample_edge
  ! Solve the heat equation (1 = yes, 0 = no) 
  public :: heat_solve
  ! Impose temperature on the free surface (only used if positive) [K]
  public :: heat_temp_surf
  ! Initial uniform temperature of the sample [K]
  public :: heat_temp_init

  ! --- Variables for the shallow water solver ---

  ! Capping height for the viscous drag in the momentum equation [m]
  public :: sw_captol
  ! Thermionic current on the free surface [A/m^2]. An array of 3
  ! elements containing: 1) the magnitude of the current,
  !  2) the switching on time, 3) the switching off time.
  ! This is only used if the heat equation is not solved,
  ! i.e. if heat.solve = 0
  public :: sw_current
  ! Dry tolerance for the melt pool [m]  (any height below dry
  ! tolerance is assumed to be zero)
  public :: sw_drytol
  ! Inclination of the magnetic field [degrees]
  public :: sw_magnetic_inclination
  ! Magnitude of the magnetic field [T]
  public :: sw_magnetic_magnitude
  ! Fixed melt velocity [m/s]. Only used if the momentum equation
  ! is not solve, i.e. sw_solve_momentum = 0
  public :: sw_melt_velocity
  ! Parameters used to generate a gaussian pool if the heat equation
  ! is not solved. An array with 3 elements containing: 1) The
  ! maximum depth of the pool [m], 2) the position of the center of the
  ! pool [m], 3) the width of the pool (as a standard deviation) [m]
  public :: sw_pool_params
  ! Solve the shallow water equation (1 = yes, 0 = no) 
  public :: sw_solve
  ! Initial position of the free surface [m] (in the heat domain,
  ! assumed perpendicular to the y-direction)
  public :: sw_surf_pos_init
  ! Solve the momentum equation (1 = yes, 0 = no). If the momentum
  ! equation is not solved, the velocity is assumed to be equal to
  ! the velocity prescribed with sw.fixed_melt_velocity
  public :: sw_solve_momentum

  ! --- Variables for the material properties ---

  ! Type of material to simulated, only one can be selected (Tungsten,
  ! Beryllium, Iridium, Niobium)
  public :: material_name
  ! Maximum temperature used to compute the material properties [K]
  public :: material_maxT
  ! Number of temperatures at which the material properties are computed
  public :: material_nPoints


  ! --- Variables that control the numerics ---

  ! Safety factor used to multiply the minimum time step
  ! that ensures the stability of the heat solver
  public :: num_cfl
  ! Relative error used in the linear solvers (only used if the implicit
  ! solver for the heat equation is employed)
  public :: num_accuracy
  ! Internal parameters for the linear solvers (only used if the implicit
  ! solver for the heat equation is employed)
  public :: num_composite_solve
  public :: num_verbose
  public :: num_bottom_verbose
  public :: num_max_iter
  public :: num_max_fmg_iter
  public :: num_bottom_solver
  public :: num_linop_maxorder
  public :: num_agglomeration
  public :: num_consolidation
  public :: num_max_coarsening_level

  
  ! --- Variables for the input/output ---

  ! Name of the restart files written by amrex
  public :: io_check_file
  ! Name of the plot files written by amrex
  public :: io_plot_file
  ! How often to write restart files (in time steps)
  public :: io_check_int
  ! How often to write output to files (in time steps)
  public :: io_plot_int
  ! Name of file use to restart the simulation
  public :: io_restart
  ! Verbosity of the code (1 = on, 0 = off)
  public :: io_verbose
  
  
  ! -----------------------------------------------------------------
  ! Public subroutines
  ! -----------------------------------------------------------------
  public :: read_input_file, deallocate_input

  ! -----------------------------------------------------------------
  ! Declare public variables
  ! -----------------------------------------------------------------

  ! Length of the simulation
  integer, save :: time_step_max
  real(amrex_real), save :: time_dt  
  real(amrex_real), save :: time_ddt_max
  real(amrex_real), save :: time_max

  ! Geometry
  character(len=:), allocatable, save :: geom_name
  real(amrex_real), allocatable, save :: geom_cool_pipe_cntr(:)
  real(amrex_real), save :: geom_cool_pipe_radius

  ! Grid
  integer, save :: regrid_int
  real(amrex_real), allocatable, save :: regrid_dist(:)

  ! Heat solver
  character(len=:), allocatable, save :: heat_solver
  character(len=:), allocatable, save :: heat_plasma_flux_type
  character(len=:), allocatable, save :: heat_plasma_flux_file
  character(len=:), allocatable, save :: heat_plasma_flux_side_type
  character(len=:), allocatable, save :: heat_plasma_flux_side_file
  character(len=:), allocatable, save :: heat_phase_init
  logical, save :: heat_cooling_thermionic
  logical, save :: heat_cooling_vaporization
  logical, save :: heat_cooling_radiation
  logical, save :: heat_reflux
  logical, save :: heat_solve
  real(amrex_real), save :: heat_sample_edge
  real(amrex_real), save :: heat_temp_surf
  real(amrex_real), save :: heat_temp_init
  real(amrex_real), allocatable, save :: heat_cooling_debug(:)
  real(amrex_real), allocatable, save :: heat_plasma_flux_params(:)
  real(amrex_real), allocatable, save :: heat_plasma_flux_side_params(:)
  
  ! Shallow water solver
  logical, save :: sw_solve
  logical, save :: sw_solve_momentum
  real(amrex_real), save :: sw_captol
  real(amrex_real), save :: sw_drytol
  real(amrex_real), save :: sw_magnetic_inclination
  real(amrex_real), save :: sw_magnetic_magnitude
  real(amrex_real), save :: sw_melt_velocity
  real(amrex_real), save :: sw_surf_pos_init
  real(amrex_real), allocatable, save :: sw_current(:)
  real(amrex_real), allocatable, save :: sw_pool_params(:)

  ! Material properties
  character(len=:), allocatable, save :: material_name
  integer, save :: material_nPoints
  real(amrex_real), save :: material_maxT
  
  ! Numerics
  integer, save :: num_verbose
  integer, save :: num_bottom_verbose
  integer, save :: num_max_iter
  integer, save :: num_max_fmg_iter
  integer, save :: num_bottom_solver
  integer, save :: num_linop_maxorder
  integer, save :: num_max_coarsening_level
  logical, save :: num_composite_solve  
  logical, save :: num_agglomeration
  logical, save :: num_consolidation
  real(amrex_real), save :: num_cfl
  real(amrex_real), save :: num_accuracy

  ! Input/output
  character(len=:), allocatable, save :: io_check_file
  character(len=:), allocatable, save :: io_plot_file
  character(len=:), allocatable, save :: io_restart   
  integer, save :: io_check_int
  integer, save :: io_plot_int
  integer, save :: io_verbose


contains

  ! ------------------------------------------------------------------
  ! Subroutine used to read the input file. Note: part of the input
  ! file is also read by the amrex initialization routines invoked
  ! with amrex_init (see the initialization module)
  ! ------------------------------------------------------------------
  subroutine read_input_file()

    type(amrex_parmparse) :: pp

    ! Default parameters
    call set_default_values

    ! Parameters for the simulation length
    call amrex_parmparse_build(pp, "time")
    call pp%query("max_step", time_step_max)
    call pp%query("stop_time", time_max)
    call pp%query("dt", time_dt)
    call pp%query("dt_change_max", time_ddt_max)
    call amrex_parmparse_destroy(pp)

    ! Parameters for the geometry
    call amrex_parmparse_build(pp, "geometry")
    call pp%query("name", geom_name)
    call pp%queryarr("cool_pipe_cntr",geom_cool_pipe_cntr)
    call pp%query("cool_pipe_radius", geom_cool_pipe_radius)
    call amrex_parmparse_destroy(pp)

    ! Parameters for the grid
    call amrex_parmparse_build(pp, "regrid")
    call pp%query("interval", regrid_int)
    call pp%queryarr("distance", regrid_dist)
    call amrex_parmparse_destroy(pp)
   
    ! Parameters for the heat solver
    call amrex_parmparse_build(pp, "heat")
    call pp%query("solve", heat_solve)  
    call pp%query("sample_edge", heat_sample_edge) 
    call pp%query("temp_init", heat_temp_init)
    call pp%query("phase_init", heat_phase_init)
    call pp%query("plasma_flux_type", heat_plasma_flux_type) 
    call pp%queryarr("plasma_flux_params", heat_plasma_flux_params)
    call pp%query("plasma_side_flux_type", heat_plasma_flux_side_type) 
    call pp%queryarr("plasma_side_flux_params", heat_plasma_flux_side_params)
    call pp%query("plasma_flux_file", heat_plasma_flux_file)
    call pp%query("plasma_side_flux_file", heat_plasma_flux_side_file)
    call pp%query("temp_free_surface", heat_temp_surf)
    call pp%query("cooling_thermionic",heat_cooling_thermionic)
    call pp%query("cooling_vaporization",heat_cooling_vaporization)
    call pp%query("cooling_radiation",heat_cooling_radiation)
    call pp%queryarr("cooling_debug",heat_cooling_debug)
    call pp%query("solver",heat_solver)
    call pp%query("reflux", heat_reflux)
    call amrex_parmparse_destroy(pp)
    
    ! Parameters for the shallow water solver
    call amrex_parmparse_build(pp, "sw")
    call pp%query("melt_velocity", sw_melt_velocity)  
    call pp%query("surf_pos_init", sw_surf_pos_init) 
    call pp%query("solve", sw_solve)
    call pp%query("solve_momentum", sw_solve_momentum)
    call pp%query("magnetic_magnitude", sw_magnetic_magnitude)
    call pp%query("magnetic_inclination", sw_magnetic_inclination)
    call pp%query("captol", sw_captol)
    call pp%query("drytol", sw_drytol)
    call pp%queryarr("current", sw_current)
    call pp%queryarr("pool_params", sw_pool_params)
    call amrex_parmparse_destroy(pp)

    ! Parameters for the numerics
    call amrex_parmparse_build(pp, "numerics")
    call pp%query("cfl", num_cfl)
    call pp%query("accuracy", num_accuracy)
    call pp%query("composite_solve", num_composite_solve)
    call pp%query("verbose", num_verbose)
    call pp%query("bottom_verbose", num_bottom_verbose)
    call pp%query("max_iter", num_max_iter)
    call pp%query("max_fmg_iter", num_max_fmg_iter)
    call pp%query("bottom_solver", num_bottom_solver)
    call pp%query("linop_maxorder", num_linop_maxorder)
    call pp%query("agglomeration", num_agglomeration)
    call pp%query("consolidation", num_consolidation)
    call pp%query("max_coarsening_level", num_max_coarsening_level)
    call amrex_parmparse_destroy(pp)

    ! Parameters for the material
    call amrex_parmparse_build(pp, "material")
    call pp%query("name", material_name)
    call pp%query("max_temperature", material_maxT)
    call pp%query("points", material_nPoints)
    call amrex_parmparse_destroy(pp)
    
    ! Parameters for input and output
    call amrex_parmparse_build(pp, "io")
    call pp%query("check_int", io_check_int)
    call pp%query("plot_int", io_plot_int)
    call pp%query("check_file", io_check_file)
    call pp%query("plot_file", io_plot_file)
    call pp%query("verbose", io_verbose)
    call pp%query("restart", io_restart)
    call amrex_parmparse_destroy(pp)
    
  end subroutine read_input_file


  ! ------------------------------------------------------------------
  ! Subroutines used to set the default values for the input variables
  ! ------------------------------------------------------------------
  subroutine set_default_values()

    ! Allocate input variables that are not scalars
    call allocate_input
    
    ! Assign default values
    call set_default_time
    call set_default_geom
    call set_default_regrid
    call set_default_heat
    call set_default_sw
    call set_default_material
    call set_default_numerics
    call set_default_io
     
  end subroutine set_default_values

  
  subroutine set_default_time()
    
    time_ddt_max = 1.1
    time_dt = 0.0001
    time_step_max = 10000
    time_max = 1.0
    
  end subroutine set_default_time

  
  subroutine set_default_geom()

    geom_name = "Slab"
    geom_cool_pipe_cntr(1) = 0.01
    geom_cool_pipe_cntr(2) = 0.005
    geom_cool_pipe_radius = 0.0

  end subroutine set_default_geom

  
  subroutine set_default_regrid()

    regrid_int = 2
    regrid_dist = 0.0_amrex_real
    
  end subroutine set_default_regrid

  
  subroutine set_default_heat()    
    
    heat_cooling_debug(1) = 0
    heat_cooling_debug(2) = 300
    heat_cooling_debug(3) = 301
    heat_cooling_debug(4) = 1
    heat_cooling_debug(5) = 1e6
    heat_cooling_thermionic = .true.
    heat_cooling_vaporization = .true.
    heat_cooling_radiation = .true.
    heat_reflux = .true.
    heat_solver = "explicit"
    heat_phase_init = "undefined"
    heat_plasma_flux_params(1) = 0.0
    heat_plasma_flux_params(2) = 1.0
    heat_plasma_flux_params(3) = 300e6
    heat_plasma_flux_params(4) = 0.0
    heat_plasma_flux_params(5) = 0.01
    heat_plasma_flux_side_params(1) = 0.0
    heat_plasma_flux_side_params(2) = 1.0
    heat_plasma_flux_side_params(3) = 300e6
    heat_plasma_flux_side_params(4) = 0.0
    heat_plasma_flux_side_params(5) = 0.01
    heat_plasma_flux_type = "Gaussian"
    heat_plasma_flux_side_type = "Gaussian"
    heat_plasma_flux_file = "plasma_flux.dat"
    heat_plasma_flux_side_file = "plasma_side_flux.dat"
    heat_solve = .true.
    heat_sample_edge = 0.020
    heat_temp_surf = -1.0
    
  end subroutine set_default_heat


  subroutine set_default_sw()

    sw_melt_velocity = 0.0
    sw_solve = .true.
    sw_solve_momentum = .true.
    sw_magnetic_magnitude = 0.0
    sw_captol = 0.0
    sw_current = 0.0
    sw_drytol = 0.0
    sw_pool_params(1) = 0.0
    sw_pool_params(2) = 0.0
    sw_pool_params(3) = 1.0
    sw_surf_pos_init = 0.020
    sw_magnetic_inclination = 90.0
    
  end subroutine set_default_sw


  subroutine set_default_material()
    
    material_name = "Tungsten"
    material_maxT = 10000.0
    material_nPoints = 10000
    
  end subroutine set_default_material

  
  subroutine set_default_numerics()

    num_cfl = 0.70
    num_accuracy = 10e-10
    num_composite_solve = .true.
    num_verbose = 0
    num_bottom_verbose = 0
    num_max_iter = 100
    num_max_fmg_iter = 0
    num_bottom_solver = amrex_bottom_default
    num_linop_maxorder = 2
    num_agglomeration = .true.
    num_consolidation = .true.
    num_max_coarsening_level = 30
    
  end subroutine set_default_numerics


  subroutine set_default_io()

    io_check_file = "chk"
    io_check_int = -1
    io_plot_file = "plt"
    io_plot_int = -1
    io_verbose = 0
    
  end subroutine set_default_io
  
  ! ------------------------------------------------------------------
  ! Subroutines used to allocate memory relate to the input variables
  ! ------------------------------------------------------------------
  subroutine allocate_input()

    call allocate_geom_variables
    call allocate_regrid_variables
    call allocate_heat_variables
    call allocate_sw_variables
    call allocate_material_variables
    call allocate_io_variables
    
  end subroutine allocate_input
  

  subroutine allocate_geom_variables()

    allocate(character(len=4)::geom_name)
    allocate(geom_cool_pipe_cntr(2))
    
  end subroutine allocate_geom_variables

  
  subroutine allocate_regrid_variables()
    
    allocate(regrid_dist(1:amrex_max_level))
        
  end subroutine allocate_regrid_variables

  
  subroutine allocate_heat_variables()

    allocate(character(len=8)::heat_solver)
    allocate(character(len=8)::heat_plasma_flux_type)
    allocate(character(len=8)::heat_plasma_flux_side_type)
    allocate(character(len=9)::heat_phase_init)
    allocate(character(len=25)::heat_plasma_flux_file)
    allocate(character(len=25)::heat_plasma_flux_side_file)
    allocate(heat_cooling_debug(5))
    allocate(heat_plasma_flux_params(100))
    allocate(heat_plasma_flux_side_params(100))
        
  end subroutine allocate_heat_variables


  subroutine allocate_sw_variables()

    allocate(sw_current(3))
    allocate(sw_pool_params(3))
        
  end subroutine allocate_sw_variables
  
  
  subroutine allocate_material_variables()

    allocate(character(len=8)::material_name)
        
  end subroutine allocate_material_variables

  
  subroutine allocate_io_variables()

    allocate(character(len=3)::io_check_file)
    allocate(character(len=3)::io_plot_file)
    allocate(character(len=0)::io_restart)
    
  end subroutine allocate_io_variables

  
  ! ------------------------------------------------------------------
  ! Subroutine used to free the memory related to the input variables
  ! ------------------------------------------------------------------  
  subroutine deallocate_input()

    call deallocate_geom_variables
    call deallocate_regrid_variables
    call deallocate_heat_variables
    call deallocate_sw_variables
    call deallocate_material_variables
    call deallocate_io_variables
    
  end subroutine deallocate_input


  subroutine deallocate_geom_variables()

    deallocate(geom_name)
    deallocate(geom_cool_pipe_cntr)
    
  end subroutine deallocate_geom_variables

  
  subroutine deallocate_regrid_variables()

    deallocate(regrid_dist)
        
  end subroutine deallocate_regrid_variables

  
  subroutine deallocate_heat_variables()

    deallocate(heat_solver)
    deallocate(heat_plasma_flux_type)
    deallocate(heat_plasma_flux_side_type)
    deallocate(heat_phase_init)
    deallocate(heat_plasma_flux_file)
    deallocate(heat_plasma_flux_side_file)
    deallocate(heat_cooling_debug)
    deallocate(heat_plasma_flux_params)
    deallocate(heat_plasma_flux_side_params)
        
  end subroutine deallocate_heat_variables


  subroutine deallocate_sw_variables()

    deallocate(sw_current)
    deallocate(sw_pool_params)
        
  end subroutine deallocate_sw_variables
  
  
  subroutine deallocate_material_variables()

    deallocate(material_name)
        
  end subroutine deallocate_material_variables

  
  subroutine deallocate_io_variables()

    deallocate(io_check_file)
    deallocate(io_plot_file)
    deallocate(io_restart)
    
  end subroutine deallocate_io_variables


end module read_input_module
